# Generated by Django 2.2.7 on 2020-04-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("avg_age", models.FloatField()),
                ("avg_daily_income", models.FloatField()),
                ("avg_daily_income_population", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="RegionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("Days", "Days"),
                            ("Weeks", "Weeks"),
                            ("Months", "Months"),
                        ],
                        default="Days",
                        max_length=20,
                    ),
                ),
                ("time_to_elapse", models.PositiveIntegerField()),
                ("reported_cases", models.PositiveIntegerField()),
                ("population", models.PositiveIntegerField()),
                ("total_hosiptal_beds", models.PositiveIntegerField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="covid_estimator.Region",
                    ),
                ),
            ],
        ),
    ]
