# Generated by Django 2.2.7 on 2020-04-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("covid_estimator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log", old_name="time_stamp", new_name="stamp",
        ),
    ]
