# Generated by Django 2.2.7 on 2020-04-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("covid_estimator", "0002_auto_20200410_1242"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log", old_name="stamp", new_name="time_stamp",
        ),
    ]
